apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: kube-ops
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
      - image: iexamcert/springboot-hello:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: springboot-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: kube-ops
  labels:
    app: springboot
spec:
  selector:
    app: springboot-demo
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    #指定nodePort为方便测试，在各环境中应注释此处nodePort避免端口造成冲突
    nodePort: 30003
