---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-2'
  tasks:
    - name: Create New Key Pair with specified Keyname
      ec2_key:
        name: sshkeypair
        region: "{{ region }}"
      register: ec2_key
    - name: save private key
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "./aws-private.pem"
        mode: 0600
      when: ec2_key.changed
