## Terminate EC2 Instance using Instance ID.
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-2'
  tasks:
    - name: Get the ec2 id
      command: cat /tmp/ec2_id
      register: ec2_id
    - name: Terminate Existing instances using Instance ID's
      ec2:
        region: "{{ region }}"
        wait: true
        instance_ids: "{{ ec2_id.stdout }}"
        state: 'absent'
